secret:
  spotify:
    client_id: ${SPOTIFY_CLIENT_ID}
    client_secret: ${SPOTIFY_CLIENT_SECRET}
  slack:
    client_id: ${SLACK_CLIENT_ID}
    client_secret: ${SLACK_CLIENT_SECRET}
    bot_token: ${SLACK_BOT_TOKEN}
    signing_secret: ${SIGNING_SECRET}

spotmystatus:
  redirect_uri_scheme: ${REDIRECT_URI_SCHEME:https}
  slack_uri: https://slack.com
  spotify_account_uri: https://accounts.spotify.com
  spotify_api_uri: https://api.spotify.com
  core_pool_size: ${CORE_POOL_SIZE:0}
  polling_rate: ${SLACK_POLLING_RATE:10000}
  passive_polling_probability: ${PASSIVE_POLLING_PROBABILITY:30}
  passivate_after_min: ${PASSIVATE_AFTER:60}
  sync_start_hr: ${PASSIVATE_START:21}
  sync_end_hr: ${PASSIVATE_END:6}
  timeout: ${POLLING_TIMEOUT:2000}
  expiration_overhead: ${EXPIRATION_OVERHEAD:120000}
  default_emojis:
    - "headphones"
    - "musical_note"
    - "notes"
  podcast_emoji: "headphones"
  default_spotify_items:
    track: "Music"
    episode: "Podcast"

spring:
  liquibase:
    change-log: classpath:/db/changelog/liquibase-changelog-master.xml
  jpa:
    database: POSTGRESQL
    open-in-view: false
  datasource:
    platform: postgres
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver

server:
  error:
    whitelabel:
      enabled: false
    path: "/dummy"